services:
  mysql:
    image: mysql:8.0.40
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BatuaaDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: password
      DB_NAME: BatuaaDB
    ports:
      - "8086:8086"
    depends_on:
      - mysql

volumes:
  mysql-data: